##################
# LOAD LIBRARIES #
##################

library(readr)
library(ggplot2)
library(tidyverse)
library(stringr)

# Get the Data

#SAIDI and SAIFI
saidi <- readr::read_csv('data - input/FINAL/SAIDI.csv', skip=1)
saifi <- readr::read_csv('data - input/FINAL/SAIFI.csv', skip=1)

df2 <- readr::read_csv("data - output/df2.csv")
energy_df <- readr::read_csv("data - output/energy_df.csv")


##############
## Analyze ##
#############
str(df2)
df2$year <- as.numeric(df2$year)

#plot renewables by emissions for US
df2 %>%
  filter(country == "United States") %>%
  filter(year < 2016) %>%
  ggplot(aes(x = year, group = 1)) +
  geom_line(aes(y=renewable_pct_all), color = "#006699", size = 1.5) +
  geom_line(aes(y=ghg_per_capita), color = "#006699", size = 1.5) +
  labs(title="Percent Energy Generated by Renewables has increased in the US since 2000",
       subtitle="while overall per capita greenhouse gas emissions have decreased slightly") +
  theme(axis.title.x = element_text(size = 12),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

#plot renewables for Europe
df2 %>%
  filter(!(country %in% "United States")) %>%
  filter(year < 2016) %>%
  ggplot(aes(x = year, group = country, color = country)) +
  geom_line(aes(y=renewable_pct_all), size = 1.5) +
  labs(title="",
       subtitle="") +
  theme(axis.title.x = element_text(size = 12),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

#add coding for US only
df2 <- df2  %>%
  mutate(country_1=ifelse(country=="United States", "1", "0"))

#pick only a few countries to plot
df2 %>%
  filter(country %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year < 2016) %>%
  filter(year >= 2010) %>%
  ggplot(aes(x = year, group = country, color = country_1)) +
  geom_line(aes(y=renewable_pct_all), size = 1.5) +
  labs(title="Percent energy generated by renewables in the US has remained relatively flat",
       subtitle="from the years 2010 to 2015",
       x = "Year") +
  scale_color_manual(values = c("1"="#669933", "0"="darkgray"), guide = FALSE )+
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 12))

df2 %>%
  filter(country %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year < 2016) %>%
  filter(year >= 2010) %>%
  ggplot(aes(x = year, group = country, color = country)) +
  geom_line(aes(y=renewable_pct_all), size = 1.5) +
  labs(title="Percent energy generated by renewables in the US has remained relatively flat",
       subtitle="from the years 2010 to 2015",
       x = "Year") +
  theme(axis.title.x = element_text(size = 12),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13))


#Slope chart, all countries, US highlighted
df2 %>%
  filter(year == 2000 | year == 2015) %>%
  ggplot(aes(x = year, group = country, color = country_1)) +
  geom_line(aes(y=renewable_pct_all), size = 1.5) +
  scale_color_manual(values = c("1"="#006699", "0"="darkgray"), guide = FALSE )+
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

#Slope chart, subset of countries
df2 %>%
  filter(country %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year == 2000 | year == 2015) %>%
  ggplot(aes(x = year, group = country, color = country_1)) +
  geom_line(aes(y=renewable_pct_all), size = 1.5) +
  scale_color_manual(values = c("1"="#006699", "0"="darkgray"), guide = FALSE )+
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

#pivot data
slope <- df2 %>%
  filter(country %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year == 2000 | year == 2015) %>%
  select(year, country, country_1, renewable_pct_all) %>%
  pivot_wider(names_from = year, values_from = renewable_pct_all)


# prep data for slope chart
left_label <- paste(slope$country, paste(round(slope$`2000`,1),'%'),sep=", ")
right_label <- paste(slope$country, paste(round(slope$`2015`,1),'%'),sep=", ")

# Plot
p <- slope %>%
  ggplot() + 
  geom_segment(aes(x=1, xend=2, y=`2000`, yend=`2015`, col=country_1), size=1.5, show.legend=F) + 
  geom_vline(xintercept=1, linetype="dashed", size=.1) + 
  geom_vline(xintercept=2, linetype="dashed", size=.1) +
  scale_color_manual(values = c("1"="#FFCC33", "0"="darkgray")) +  # color of lines
  labs(x="", y="Percent Renewable Energy Generation") +  # Axis labels
  xlim(.5, 2.5) + ylim(0,(1.1*(max(slope$`2015`))))  # X and Y axis limits

# Add texts
p <- p + geom_text(label=left_label, y=slope$`2000`, x=rep(1, NROW(df)), hjust=1.1, size=3.5)
p <- p + geom_text(label=right_label, y=slope$`2015`, x=rep(2, NROW(df)), hjust=-0.1, size=3.5)
p <- p + geom_text(label="2000", x=1, y=32, hjust=1.2, size=5)  # title
p <- p + geom_text(label="2015", x=2, y=32, hjust=-0.1, size=5)  # title

# Minify theme
p + theme(panel.background = element_blank(), 
          panel.grid = element_blank(),
          axis.ticks = element_blank(),
          axis.text.x = element_blank(),
          panel.border = element_blank(),
          axis.title.y = element_text(size =13))

#save
ggsave("plots/renewable_pct.png", dpi = "retina")


#percent thermal
df2 %>%
  filter(country %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year < 2016) %>%
  filter(year >= 2010) %>%
  ggplot(aes(x = year, group = country, color = country_1)) +
  geom_line(aes(y=thermal_pct), size = 1.5) +
  scale_color_manual(values = c("1"="#990000", "0"="darkgray"), guide = FALSE )+
  labs(title="As of 2015, the US had the highest percent generated by thermal sources",
       subtitle="compared to France, Germany, Ireland, and the UK",
       x = "Year") +
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 12))

##############
## Emissions #
################

#calculate world average by year
df2 %>%
  group_by(year) %>%
  filter(year == 2016)%>%
  summarise(average = mean(ghg_per_capita, na.rm = TRUE))

df2_2016 <- df2 %>%
  filter(year == 2016)

df2_2016 <- df2_2016 %>%
  mutate(ghg_z = (ghg_per_capita - mean(ghg_per_capita, na.rm = TRUE))/sd(ghg_per_capita, na.rm = TRUE))  # compute normalized mpg

df2_2016$ghg_type <- ifelse(df2_2016$ghg_z < 0, "below", "above")  # above / below avg flag
df2_2016 <- df2_2016[order(df2_2016$ghg_z), ]  # sort
df2_2016$country <- factor(df2_2016$country, levels = df2_2016$country)


df2_2016 %>%
  filter(!(country %in% c("The Netherlands","Lithuania"))) %>%
  ggplot(aes(x=country, y=ghg_z, label=ghg_z)) + 
  geom_bar(stat='identity', aes(fill=ghg_type), width=.5)  +
  scale_fill_manual(name="Emissions", 
                    labels = c("Above Average", "Below Average"), 
                    values = c("above"="#FFCC33", "below"="darkgray")) + 
  coord_flip() +
  theme(axis.title.x = element_blank(),
        axis.text.y = element_text(size =12),
        axis.title.y = element_blank(),
        panel.background = element_blank())

ggsave('plots/emissions.png', dpi = "retina")

#make a bar chart comparing the countries to global average

df2 %>%
  filter(country %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year == 2000 | year == 2015) %>%
  ggplot(aes(x = year, group = country, color = country_1)) +
  geom_line(aes(y=ghg_per_capita), size = 1.5) +
  scale_color_manual(values = c("1"="#006699", "0"="darkgray"), guide = FALSE )+
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

df2 %>%
  filter(country %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year < 2016) %>%
  filter(year >= 2010) %>%
  ggplot(aes(x = year, group = country, color = country_1)) +
  geom_line(aes(y=ghg_per_capita), size = 1.5) +
  scale_color_manual(values = c("1"="#990000", "0"="darkgray"), guide = FALSE )+
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

df2 %>%
  filter(country %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year == 2015) %>%
  ggplot(aes(x = country, y=ghg_per_capita, fill = country_1)) +
  geom_col() +
  scale_fill_manual(values = c("1"="#990000", "0"="darkgray"), guide = FALSE )+
  labs(y = "Greenhouse gas emissions per capita") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(13),
        axis.text.y = element_text(13),
        panel.background = element_blank(),
        legend.position = "")


###############
# reliability #
#############3#

#plot SAIDI - bar
df2 %>%
  filter(country %in% c("United States","United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year == 2016) %>%
  ggplot(aes(x = reorder(country, SAIDI), y = SAIDI, fill = country_1, label = round(SAIDI))) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("1"="#FFCC33", "0"="darkgray"), guide = FALSE )+
  geom_text(vjust =1.5 , color = "black", size = 4) +
  labs(title = "System Average Interruption Duration Index (SAIDI) measured in minutes",
       subtitle = "The US has the highest SAIDI out of these countries with higher renewable energy generation") +
  theme(axis.text.x = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

ggsave("plots/saidi.png", dpi = "retina", width=20, height =20, units = "cm")

#plot SAIFI - bar
df2 %>%
  filter(country %in% c("United States","United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(year == 2016) %>%
  ggplot(aes(x = reorder(country, SAIFI), y = SAIFI, fill = country_1, label = SAIFI)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("1"="#FFCC33", "0"="darkgray"), guide = FALSE )+
  geom_text(vjust =1.5 , color = "black", size = 4) +
  labs(title = "System Average Interruption Frequency Index (SAIFI) measured in interruptions per customer",
       subtitle = "The US also has the highest SAIFI out of these countries with higher renewable energy generation") +
  theme(axis.text.x = element_text(size = 12),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

ggsave("plots/saifi.png", dpi = "retina", width=20, height =20, units = "cm")


df2 %>%
  filter(country %in% c("United States", "Germany")) %>%
  filter(year < 2017) %>%
  filter(year >= 2013) %>%
  ggplot(aes(x = year, group = country, color = country_1)) +
  geom_line(aes(y=SAIDI), size = 1.5) +
  scale_color_manual(values = c("1"="#006699", "0"="darkgray"), guide = FALSE )+
  theme(axis.title.x = element_text(size = 12),
        axis.title.y = element_blank(),
        panel.background = element_blank(),
        plot.title = element_text(size = 13),
        legend.position = "")

#plot percent thermal and renewable
df2 %>%
  filter(country %in% c("United States", "Germany")) %>%
  filter(year < 2016) %>%
  filter(year >= 2013) %>%
  ggplot(aes(x = year, group = country, color = country_1)) +
  geom_line(aes(y=thermal_pct), size = 1.5) +
  geom_line(aes(y=renewable_pct_all), size = 1.5, linetype = "dashed") +
  scale_color_manual(values = c("1"="#006699", "0"="darkgray"), guide = FALSE )+
  theme(axis.title.x = element_text(size = 12),
            axis.title.y = element_blank(),
            panel.background = element_blank(),
            plot.title = element_text(size = 13),
            legend.position = "")



########
# mix #
########

energy_df %>%
  filter(country_name %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(type %in% c('Geothermal','Nuclear','Wind','Hydro','Solar')) %>%
  ggplot(aes(x = year, y = per_capita_kwh, color = type)) +
  geom_point() +
  facet_wrap(~country_name)

#highlight wind
energy_df %>%
  filter(country_name %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(!(type %in% c('% Renewable', 'Coal', 'Crude Oil', 'Natural Gas','Total Renewable', 'Geothermal','Other',
  'Total'))) %>%
  filter(year == '2016') %>%
  ggplot(aes(x = country_name, y = per_capita_kwh, fill = type)) +
  scale_fill_manual(values = c("Wind"="#FFCC33", "Conventional thermal"="darkgray", "Solar" ="darkgray", 
                               "Hydro" ="darkgray", "Nuclear" = "darkgray"))+
  geom_bar(position = "fill",stat = "identity") +
  ylab("Percent per capita kwh") +
  coord_flip() +
  theme(axis.text.y = element_text(size = 12),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size=12),
        panel.background = element_blank())

ggsave('plots/wind.png',width=25, height =15, units = "cm", dpi="retina")

#highlight solar
energy_df %>%
  filter(country_name %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(!(type %in% c('% Renewable', 'Coal', 'Crude Oil', 'Natural Gas','Total Renewable', 'Geothermal','Other',
                       'Total'))) %>%
  filter(year == '2016') %>%
  ggplot(aes(x = country_name, y = per_capita_kwh, fill = type)) +
  scale_fill_manual(values = c("Wind"="#FFCC33", "Conventional thermal"="darkgray", "Solar" ="#669900", 
                               "Hydro" ="darkgray", "Nuclear" = "darkgray"))+
  geom_bar(position = "fill",stat = "identity") +
  ylab("Percent per capita kwh") +
  coord_flip() +
  theme(axis.text.y = element_text(size = 12),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size=12),
        panel.background = element_blank())

ggsave('plots/solar.png',width=25, height =15, units = "cm", dpi="retina")

#highlight nuclear
energy_df %>%
  filter(country_name %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(!(type %in% c('% Renewable', 'Coal', 'Crude Oil', 'Natural Gas','Total Renewable', 'Geothermal','Other',
                       'Total'))) %>%
  filter(year == '2016') %>%
  ggplot(aes(x = country_name, y = per_capita_kwh, fill = type)) +
  scale_fill_manual(values = c("Wind"="#FFCC33", "Conventional thermal"="darkgray", "Solar" ="#669900", 
                               "Hydro" ="darkgray", "Nuclear" = "burlywood4"))+
  geom_bar(position = "fill",stat = "identity") +
  ylab("Percent per capita kwh") +
  coord_flip() +
  theme(axis.text.y = element_text(size = 12),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size=12),
        panel.background = element_blank())

ggsave('plots/nuclear.png',width=25, height =15, units = "cm", dpi="retina")

#highlight nuclear
energy_df %>%
  filter(country_name %in% c("United States", "United Kingdom", "Germany", "France", "Ireland")) %>%
  filter(!(type %in% c('% Renewable', 'Coal', 'Crude Oil', 'Natural Gas','Total Renewable', 'Geothermal','Other',
                       'Total'))) %>%
  filter(year == '2016') %>%
  ggplot(aes(x = country_name, y = per_capita_kwh, fill = type)) +
  scale_fill_manual(values = c("Wind"="#FFCC33", "Conventional thermal"="darkgray", "Solar" ="#669900", 
                               "Hydro" ="darkblue", "Nuclear" = "burlywood4"))+
  geom_bar(position = "fill",stat = "identity") +
  ylab("Percent per capita kwh") +
  coord_flip() +
  theme(axis.text.y = element_text(size = 12),
        axis.title.y = element_blank(),
        axis.title.x = element_text(size=12),
        panel.background = element_blank())

ggsave('plots/hydro.png',width=25, height =15, units = "cm", dpi="retina")

#what are percents of each group
pct <- energy_df %>%
  filter(!(type %in% c('% Renewable', 'Coal', 'Crude Oil', 'Natural Gas','Total Renewable', 'Geothermal','Other'))) %>%
  select(country_name, year, per_capita_kwh, type) %>%
  pivot_wider(names_from = type, values_from = per_capita_kwh) %>%
  filter(year == '2016') %>%
  mutate(pct_wind = (Wind/(`Conventional thermal`+Wind+Solar+Hydro+Nuclear))*100) %>%
  mutate(pct_solar = (Solar/(`Conventional thermal`+Wind+Solar+Hydro+Nuclear))*100) %>%
  mutate(pct_nuclear = (Nuclear/(`Conventional thermal`+Wind+Solar+Hydro+Nuclear))*100) %>%
  mutate(pct_hydro = (Hydro/(`Conventional thermal`+Wind+Solar+Hydro+Nuclear))*100)
